name: confwebsite2023
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0-42.2.beta <4.0.0"
  flutter: ">=3.14.0-0.2.pre"

dependencies:
  animations: ^2.0.7
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.6
  flutter_linkify: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.17+3
  flutter_svg: ^2.0.7
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^11.0.0
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.3.6
  http: ^1.0.0
  intl: ^0.18.1
  js: ^0.6.7
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1
  transparent_image: ^2.0.1
  url_launcher: ^6.1.11
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  go_router_builder: ^2.3.3
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/app_links/
    - assets/icons/
    - assets/sponsors/
    - assets/

flutter_gen:
  output: lib/core/gen/
